ignored = ["local/*"]


required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen"
]

[[constraint]]
  name = "github.com/go-acme/lego"
  version = "v2.5.0"

[[constraint]]
  name = "github.com/gardener/controller-manager-library"
  branch = "master"

[[constraint]]
  name = "github.com/gardener/external-dns-management"
  version = "0.6.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.4"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.4"

# Dependencies for testing purposes only
[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.8.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
