apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoheaders
  namespace: default
  labels:
    garden.sapcloud.io/purpose: managed-cert
spec:
  tls:
    - hosts:
        - echoheaders.demo.mydomain.com
      secretName: cert-echoheaders
  rules:
    - host: echoheaders.demo.mydomain.com
      http:
        paths:
          - backend:
              serviceName: echoheaders
              servicePort: 80
            path: /
